'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18449
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="ServiceUsuarios", ConfigurationName:="ServiceReference1.ServicioUsuarios")>  _
    Public Interface ServicioUsuarios
        
        <System.ServiceModel.OperationContractAttribute(Action:="ServiceUsuarios/ServicioUsuarios/consultarUsuarios", ReplyAction:="ServiceUsuarios/ServicioUsuarios/consultarUsuariosResponse")>  _
        Function consultarUsuarios() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="ServiceUsuarios/ServicioUsuarios/consultarUsuarios", ReplyAction:="ServiceUsuarios/ServicioUsuarios/consultarUsuariosResponse")>  _
        Function consultarUsuariosAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServicioUsuariosChannel
        Inherits ServiceReference1.ServicioUsuarios, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioUsuariosClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ServicioUsuarios)
        Implements ServiceReference1.ServicioUsuarios
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function consultarUsuarios() As String Implements ServiceReference1.ServicioUsuarios.consultarUsuarios
            Return MyBase.Channel.consultarUsuarios
        End Function
        
        Public Function consultarUsuariosAsync() As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.ServicioUsuarios.consultarUsuariosAsync
            Return MyBase.Channel.consultarUsuariosAsync
        End Function
    End Class
End Namespace
